name: Publish Docker image
on:
  push:
    branches:
      - main
      - ci

jobs:
  build:
    name: qt-android-cmake
    runs-on: ubuntu-latest

    strategy:
      matrix:
        qt-version: ['5.12.9', '5.15.1']
        api: ['26', '28', '29']
        ndk: ['28.0.3']

    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Push to Docker Hub
        uses: docker/build-push-action@v2
        with:
          build-args: qt-version=${{ matrix.qt-version }},api=${{ matrix.api }},ndk=${{ matrix.ndk }}
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/qt-android-cmake:qt${{ matrix.qt-version }}-api${{ matrix.api }}-ndk${{ matrix.ndk }}
      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}